#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          15

bspc config normal_border_color "#9faca3"
bspc config focused_border_color "#6a938b"
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout br,kr -option 'grp:alt_shift_toggle'
xrandr --output VGA1 --mode 1360x768
feh --bg-fill /home/george/Wallpapers/unsplash2.jpg
compton
polybar top
